

#ifndef STRING_TABLE_H_
#define STRING_TABLE_H_

extern const char*  string_table[];

typedef enum {
	AT_RESET,
	AT_ECHO_OFF,
	AT_SIM_CHECK,
	AT_NETWORK_STATUS,
	AT_SIGNAL_QUALITY,
	AT_IMEI_GET,
	AT_CNCONFIG_CONTYPE,
	AT_CNCONFIG_SETAPN,
	AT_CNCONFIG_SETUSER,
	AT_CNCONFIG_SETPWD,
	AT_CNCONFIG_SETPROFILE,
	AT_CNCONFIG_QUERY,
	AT_HTTP_INIT,
	AT_HTTP_SETPROFILE,
	AT_HTTP_SETURL,
	AT_HTTP_GET,
	AT_HTTP_POST,
	AT_HTTP_READ,
	AT_HTTP_TERM,
	AT_HTTP_DATA,
	AT_OK,
	URL_LOG0,
	URL_LOG1,
	URL_LOG2,
	URL_LOG3,
	URL_LOG4,
	AT_GET_TIME,
	AT_SET_TIME,
	RESPONSE_SIM_STATUS,
	RESPONSE_NETWORK_STATUS,
	RESPONSE_SIGNAL_QUALITY,
	RESPONSE_HTTP_GET,
	RESPONSE_HTTP_READ,
	RESPONSE_OK,
	RESPONSE_CN_STATUS,
	CRLF,
	AT_GPRS_ON,
	AT_GPRS_OFF
} StringTableIndicesType;

#endif
